#!/bin/bash

echo "Running postinstall" > ~/Desktop/jre_install.log

if type -p java; then
  echo found java executable in PATH >> ~/Desktop/jre_install.log
  _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
  echo found java executable in JAVA_HOME >> ~/Desktop/jre_install.log
  _java="$JAVA_HOME/bin/java"
else
  echo "no java" >> ~/Desktop/jre_install.log
fi

if [[ "$_java" ]]; then
  version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
  echo version "$version" >> ~/Desktop/jre_install.log
  if [[ "$version" == "1.7.0_80" ]]; then
    echo "version is 1.7.0_80" >> ~/Desktop/jre_install.log
    rm ~/Desktop/jre_install.log
    exit 0
  else
    echo "java version is NOT 1.7. It is $version" >> ~/Desktop/jre_install.log
    exit 1
  fi
fi
